FROM java:8-jre
WORKDIR /usr/src

COPY ./target/GipherFavouriteModule-0.0.1-SNAPSHOT.jar GipherFavouriteModule-0.0.1-SNAPSHOT.jar
#EXPOSE 8082
ENTRYPOINT ["java","-jar","/usr/src/GipherFavouriteModule-0.0.1-SNAPSHOT.jar"]
